name: CI

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: wakeupver/kernel_build_action@main
        with:
          kernel-url: https://github.com/wakeupver/android_kernel_xiaomi_sdm845_los
          kernel-branch: lineage-20
          config: vendor/xiaomi/mi845_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          # aosp-clang-version: r547379
          other-clang-url: https://github.com/kdrag0n/proton-clang.git
          other-clang-branch: master
          ksu: true
          ksu-other: true
          ksu-version: legacy
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next
          anykernel3: true
          extra-make-args: CROSS_COMPILE_ARM32=arm-linux-gnueabi-
