name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/PainKiller3/android_kernel_xiaomi_sdm845
          kernel-branch: thirteen
          config: vendor/xiaomi/silvercore_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang.git
          other-clang-branch: master
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next
          anykernel3: true
